config/routes.rb
Rails.application.routes.draw do
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'logout'  => 'sessions#destroy'

  get    'area/new_advert'   => 'advertiser_area#new'
  get    'area/edit_advert'   => 'advertiser_area#edit'
  get    'area/index_advert'   => 'advertiser_area#index'
  get    'area/sales_adverts' =>  'advertiser_area#sales'
  post   'area/create_advert'   => 'advertiser_area#create'
  delete 'area/destroy_advert'  => 'advertiser_area#destroy'

  get     'new_advert' => 'adverts#new'

  get     'index' => 'adverts#index'

  resources :users
  resources :tests
  resources :adverts

end

app/models/advert.rb
class Advert < ActiveRecord::Base
  belongs_to :advertiser
  belongs_to :category
end

app/models/advert_detail.rb
class AdvertDetail < ActiveRecord::Base
end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  has_many :adverts
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/provincium.rb
class Provincium < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/advertiser_area_controller.rb
class AdvertiserAreaController < ApplicationController
  before_action :check_auth, only: [:edit, :update]
  before_action :get_advert, only: [:edit, :update, :check_auth]
  before_action :logged_in_user, only: [:new]


  def get_advert
    @advert = Advert.find(params[:id])
  end

  def check_auth
    if session[:advertiser_id]!=@advert.advertiser_id
      flash[:notice]="Sorry, you are not allowed to do this operation"
      redirect_to login_url
    end
  end

  def index
  end

  def new
    @advertisers=Advertiser.all
    @categories=Category.all
    @adverts = Advert.new
    @countries = Country.all
    @states = State.all
  end

  def edit
  end

  def create
    @advert = Advert.new(advert_params)
    @advert.save
    redirect_to @advert
  end

  def show
  end

  private
  def advert_params
    params.require(:advert).permit(:title, :description, :photo, :type, :category_id, :contactphone, :advertiser_id, :city, :state, :country)
  end

    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/helpers/advertiser_area_helper.rb
module AdvertiserAreaHelper
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/adverts_helper.rb
module AdvertsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
    session[:advertiser_id]= user.advertiser_id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_advertiser
    @current_advertiser ||= User.find_by(id: session[:user_id]).advertiser_id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/state_helper.rb
module StateHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/advertiser_area/_header.html.haml
-@logo="adverts/logo.png"
%header.putcolor
  =image_tag("adverts/cabecera.jpg")
  .capt
    .row.putcolor
      .small-12.columns
        .txt-helper
          .txt
            %h1.main_h1
              %span.wrap Un anuncio...
            %h2.main_h2
              %span.wrap ...una nueva oportunidad

app/views/advertiser_area/_menu2.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      %button{type: "button", class:"navbar-toggle", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
        %span{class:"icon-bar"}
        %span{class:"icon-bar"}
        %span{class:"icon-bar"}
    %a.navbar-brand.text-logo{href: "#"}
      %i.icon-signout
        = content_for :window_title
    .navigation.navbar-collapse.collapse
      %ul.nav.navbar-nav.menu-right
        %li.active
          %a{href:"#belleza"}
            Belleza y estética
        %li
          %a{href:"#moda"}
            Moda
        %li
          %a{href:"#restaurantes"}
            Restaurantes
        %li
          %a{href:"#ocio"}
            Ocio
        %li
          %a{href:"#salud"}
            Salud
        %li
          %a{href:"#otros"}
            Otros

app/views/advertiser_area/edit.html.haml
=render partial: "menu"
%h1 Editing test

= render 'form'

= link_to 'Show', @advert
\|
= link_to 'Back', advert_path

app/views/advertiser_area/new.html.haml
=render partial: "header"
=render partial: "menu2"
.container.putcolor
  .center.jumbotron
    = form_for @adverts, as: "advert", url: adverts_path, html: { class: "form-horizontal" }  do |f|
      .row.col-sm-10
        .form-group
        .row
          .col-sm-1
            = f.label :title, :caption => "Title or Claim: ", :class => 'control-label'
          .col-sm-11
            = f.text_field :title, :placeholder => current_user, :class => 'form-control'
        .form-group
        .row
          .col-sm-1
            = f.label :description, :caption => "Description:", :class => 'control-label'
          .col-sm-11
            = f.text_area :description, :placeholder => "Description", :class => 'form-control'
        .form-group
        .row
          .col-sm-1
            = f.label :photo, :caption => "Photo or imag:", :class => 'control-label'
          .col-sm-5
            = f.text_field :photo, :placeholder => "Photo ", :class => 'form-control'
            //= f.file_field :photo, :placeholder => "Photo or image", :class => 'form-control'
        .form-group
        .row
          .col-sm-1
            = f.label :category_id, :caption => "Category:", :class => 'control-label'
          .col-sm-3
            = f.select :advertiser_id,  options_for_select(@categories.collect { |fa|[fa.category.titleize, fa.id] }, 1), {}, :class => 'form-control'
          .col-sm-8
        .form-group
        .row
          .col-sm-1
            = f.label :country, :caption => "Country:", :class => 'control-label'
          .col-sm-3
            = f.select :country,  options_for_select(@countries.collect { |fa|[fa.country_name.titleize] }, 1), {}, :class => 'form-control'
          .col-sm-8
        .form-group
        .row
          .col-sm-1
            = f.label :state, :caption => "State:", :class => 'control-label'
          .col-sm-3
            = f.select :state,  options_for_select(@states.collect { |fa|[fa.state_name.titleize] }, 1), {}, :class => 'form-control'
          .col-sm-8
        .form-group
        .row
          .col-sm-1
            = f.label :postal, :caption => "Postal Code:", :class => 'control-label'
          .col-sm-2
            = f.text_field :postal, :placeholder => "Postal Code", :class => 'form-control'
          .col-sm-1
            = f.label :contactphone, :caption => "Contact Phone:", :class => 'control-label'
          .col-sm-2
            = f.text_field :contactphone, :placeholder => "900000000", :class => 'form-control'
          .col-sm-1
            = f.label :advertiser_id, :caption => "advertiser_id:", :class => 'control-label'
          .col-sm-2
            = f.select :advertiser_id,  options_for_select(@advertisers.collect { |fa|[fa.tradename.titleize, fa.id] }, 1), {}, :class => 'form-control'
        .form-group
        .row
          .col-sm-10
            = f.submit "Submit" , :class=> "btn btn-primary btn-lg"
    .row
      .col-sm-12
        .form-process-contact